export const products = [
  {
    id: "1",
    title: "GoPro Action Camera 32GB Waterproof",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/gopro.jpg"],
    categories: ["Electrics"],
  },
  {
    id: "2",
    title: "Non-ticking Wooden  Wall Clock",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/glasses.jpg"],
    categories: ["Clothing"],
  },
  {
    id: "3",
    title: "Bag",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/smartwatch.jpg"],
    categories: ["Watch"],
  },
  {
    id: "4",
    title: "Shoose",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/chair.jpg"],
    categories: ["Home"],
  },
  {
    id: "5",
    title: "Macbook",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/macbook.jpg"],
    categories: ["Laptop"],
  },
  {
    id: "6",
    title: "Smart Watch",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/smartwatch2.jpg"],
    categories: ["Home"],
  },
  {
    id: "7",
    title: "Fast charger",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/charger.jpg"],
    categories: ["Electrics"],
  },
  {
    id: "8",
    title: "Apple Imac",
    oldPrice: "20.00",
    currentPrice: "18.00",
    images: ["/images/products/imac.jpg"],
    categories: ["Laptop"],
  },
];
